[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"
vicmd_symbol = "[V](bold green)"

[cmd_duration]
style = "white bold"

[python]
style = "blue bold"

[cmake]
symbol = "CMake "
style = "fg:green bg:8"

[gcloud]
disabled = true

